### ISSUE TITLE
I cannot select MyCredentialManager to manage Passkey

### ISSUE THREAD

**Issue by jekinleeph** [ko-koiwai/MyCredentialManager#1]
The system of the pixel 7 I am using has been updated to Android 14, and Chrome has been updated to the latest version. After installing the MyCredentialManager application, turn on the switch in "setting - password & account", use chrome to open webauthn.io to register a key. In the pop-up window, I cannot select MyCredentialManager to manage Passkey. What else do I need to do to get it work through?

**Comment by ko-koiwai** [comment]
Thanks for trying!
did you set `chrome://flags/#web-authentication-android-credential-management` ?

**Comment by jekinleeph** [comment]
> Thanks for trying! did you set `chrome://flags/#web-authentication-android-credential-management` ?

Thanks! it works.
